import Head from 'next/head';
import { Tomorrow } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const tomorrow = Tomorrow({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Relative assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="mx-20 mt-60">
          <div className="flex gap-4">
            <img src="/icons/trending.svg" alt='trending icon' />
            <p className={tomorrow.className}>Trending Assets</p>
          </div>
        </div>
      </main>
    </>
  );
}
